const DAYS=[
{date:'10/14',dow:'WED',short:'淺草',label:'DAY 1 · ARRIVAL',title:'淺草 → 晴空塔',sub:'抵達東京後，輕鬆夜拍',spots:[['15:20','成田國際機場','Peach MM626 抵達','Narita International Airport',''],['17:45','Hotel Sardonyx Ueno','Check-in · 放行李','Hotel Sardonyx Ueno','機場 → 上野｜約 60–80 分'],['19:00','淺草寺 · 雷門','夜拍 · 周邊散步','Senso-ji Tokyo','上野 → 淺草｜約 15–25 分'],['20:15','東京晴空塔','Solamachi · 夜景','Tokyo Skytree','淺草 → 晴空塔｜約 15–25 分']],near:[['淺草寺','景點'],['雷門','拍照'],['東京晴空塔','景點'],['Tokyo Solamachi','購物']],check:['淺草伴手禮','晴空塔限定商品']},
{date:'10/15',dow:'THU',short:'原宿',label:'DAY 2 · SHOPPING',title:'豪德寺 → 下北澤 → 原宿 → 澀谷',sub:'招財貓、香氛、日系品牌',spots:[['08:00','上野出發','早餐後出發','Hotel Sardonyx Ueno',''],['09:00','豪德寺','招財貓 · 拍照｜必去','Gotokuji Temple','上野 → 豪德寺｜約 55–70 分'],['11:00','APFR TOKYO','下北澤香氛｜必去','APFR TOKYO Shimokitazawa','豪德寺 → 下北澤｜約 30–45 分'],['13:30','青山 · 原宿購物','Graphpaper → Goldwin → New Balance → ASICS','Graphpaper AOYAMA','下北澤 → 青山｜約 35–45 分'],['18:00','澀谷','KITH · 晚餐 · 夜拍','Shibuya Scramble Crossing','原宿 → 澀谷｜步行約 15–25 分']],near:[['APFR TOKYO','必去'],['Graphpaper AOYAMA','順路'],['Goldwin Harajuku','順路'],['New Balance Harajuku','順路'],['ASICS FLAGSHIP HARAJUKU','順路'],['KITH TOKYO','順路'],['nanamica DAIKANYAMA','備選']],check:['APFR TOKYO','Graphpaper','Goldwin','New Balance','ASICS','KITH TOKYO']},
{date:'10/16',dow:'FRI',short:'Pokémon',label:'DAY 3 · POKÉMON',title:'PokéPark KANTO ⚡',sub:'今天就是 Pokémon Day',spots:[['08:00','上野出發','前往讀賣樂園','Yomiuriland Tokyo',''],['10:00','PokéPark KANTO','提早抵達 · 入園準備','Yomiuriland Tokyo','上野 → 讀賣樂園｜約 80–100 分'],['11:00','Pokémon Forest','11:00–12:00｜固定票券','Yomiuriland Tokyo',''],['12:00','PokéPark 園區','拍照 · 午餐 · 商品','Yomiuriland Tokyo',''],['17:30','Shibuya PARCO','Pokémon Center · Nintendo TOKYO','Pokemon Center SHIBUYA','PokéPark → 澀谷｜約 70–90 分']],near:[['Pokémon Center SHIBUYA','必逛'],['Nintendo TOKYO','必逛'],['Shibuya PARCO','購物'],['KITH TOKYO','可補逛']],check:['PokéPark 限定商品','Pokémon Center SHIBUYA','Nintendo TOKYO']},
{date:'10/17',dow:'SAT',short:'銀座',label:'DAY 4 · TOKYO CITY',title:'銀座 → 麻布台 → 東京鐵塔',sub:'購物、建築與東京夜景',spots:[['10:30','銀座','先逛銀座街區','Ginza Tokyo',''],['11:00','On Flagship Store Tokyo Ginza','主要購物點','On Flagship Store Tokyo Ginza',''],['12:00','銀座自由購物','UNIQLO · MUJI · Loft · GINZA SIX','GINZA SIX','銀座店家集中｜步行'],['15:30','麻布台之丘','建築 · 商場 · 拍照','Azabudai Hills','銀座 → 麻布台｜約 20–30 分'],['18:00','東京鐵塔','夕景 · 夜景','Tokyo Tower','麻布台 → 東京鐵塔｜步行約 15–25 分']],near:[['On Flagship Store Tokyo Ginza','高優先'],['UNIQLO Ginza','順逛'],['MUJI Ginza','順逛'],['Ginza Loft','順逛'],['GINZA SIX','順逛'],['麻布台之丘','主景點'],['東京鐵塔','主景點'],['築地場外市場','早起才加']],check:['On Ginza','銀座伴手禮','麻布台想買的東西']},
{date:'10/18',dow:'SUN',short:'上野',label:'DAY 5 · LAST DAY',title:'上野東照宮 → 伴手禮 → 成田',sub:'最後採買，安心前往機場',spots:[['08:30','飯店早餐 · 整理行李','完成退房準備','Hotel Sardonyx Ueno',''],['09:00','上野東照宮','昇龍守優先｜必去','Ueno Toshogu Shrine','飯店 → 上野公園｜約 15–25 分'],['10:15','阿美橫町','伴手禮 · 最後採買','Ameyoko Shopping District','東照宮 → 阿美橫町｜步行約 15–20 分'],['11:30','回飯店取行李','簡單午餐後準備出發','Hotel Sardonyx Ueno',''],['12:30','前往成田機場','目標 14:00–14:20 抵達','Narita International Airport','上野 → 成田｜約 45–70 分'],['16:50','NRT → TPE','Peach MM625 · 19:40 抵達','Narita International Airport','']],near:[['上野東照宮','限定御守'],['上野公園','散步'],['阿美橫町','伴手禮'],['多慶屋','備選']],check:['上野東照宮・昇龍守','伴手禮','回飯店取行李']}
];
let day=0,tab='trip'; const app=document.querySelector('#app');
const maps=q=>'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q); const key=(d,i)=>`tokyo26-check-${d}-${i}`;
function checked(d,i){return localStorage.getItem(key(d,i))==='1'}
function render(){let d=DAYS[day],done=d.check.filter((_,i)=>checked(day,i)).length;app.innerHTML=`<div class="wrap"><header class="top"><div class="eyebrow">EASON'S TOKYO TRIP</div><h1>東京 · 5 DAYS</h1><div class="sub">2026.10.14 — 10.18 · UENO</div></header><nav class="days">${DAYS.map((x,i)=>`<button class="day ${i===day?'active':''}" data-day="${i}"><small>${x.dow}</small><b>${x.date}</b><small>${x.short}</small></button>`).join('')}</nav><section class="hero"><div class="eyebrow">${d.label}</div><h2>${d.title}</h2><div class="sub">${d.sub}</div><div class="tabs"><button class="tab ${tab==='trip'?'active':''}" data-tab="trip">行程</button><button class="tab ${tab==='near'?'active':''}" data-tab="near">附近想逛</button><button class="tab ${tab==='check'?'active':''}" data-tab="check">CHECK ${done}/${d.check.length}</button></div></section>${panel(d)}<div class="footer">2026 TOKYO · EASON</div></div>`;bind()}
function panel(d){if(tab==='trip')return d.spots.map((s,i)=>`${i&&s[4]?`<div class="move">↓ ${s[4]}</div>`:''}<div class="timeline"><div class="time">${s[0]}</div><div class="card place"><h3>${s[1]}</h3><p>${s[2]}</p><a class="mapbtn" href="${maps(s[3])}" target="_blank">Google Maps ↗</a></div></div>`).join('');if(tab==='near')return `<p class="hint">保留所有想去的店，但不強迫塞進固定時間。</p><div class="list">${d.near.map(n=>`<a class="card row" href="${maps(n[0])}" target="_blank"><span><b>${n[0]}</b><br><small class="sub">${n[1]}</small></span><span>↗</span></a>`).join('')}</div>`;return `<p class="hint">買到或完成就勾掉；關掉網站後仍會保留。</p><div class="list">${d.check.map((x,i)=>`<label class="card check ${checked(day,i)?'done':''}"><input type="checkbox" data-check="${i}" ${checked(day,i)?'checked':''}><span>${x}</span></label>`).join('')}</div>`}
function bind(){document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{day=+b.dataset.day;tab='trip';render()});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});document.querySelectorAll('[data-check]').forEach(c=>c.onchange=()=>{localStorage.setItem(key(day,+c.dataset.check),c.checked?'1':'0');render()})}
render(); if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
